### ISSUE TITLE
Hey Alex!

### ISSUE THREAD

**Issue by Cthonicat** [alegian/thaumcraft7#1]
Hey Alex,

I saw you are working towards updating Thaumcraft for modern versions of minecraft! Admittedly I have no idea how to code: i actually made this github account for the sole purpose of contacting you (sorry if this is the wrong area to comment in or if there is a dedicated area to make comments in). I was wondering if you needed help with any aspects of this project; for instance, i'd love to design pixel art or help write thaumonomicon entries if you'd let me! I've dabbled in pixel art in the past and am willing to provide samples of my writing if you'd like. I'm also very willing to learn more regarding making textures / converting over old ones. If any of that sounds interesting to you or if you'd just like to talk shoot me a dm!

**Comment by alegian** [comment]
hello! i have sent you a discord friend request, so we can discuss this further! Thank you for the interest!

I have force edited this issue to censor your private information, but I saved the contact details before doing so.
